In [3]:
import numpy as np

loaded_data = np.loadtxt('/content/drive/MyDrive/Colab Notebooks/2022_1학기_인공지능/Data/data-01.csv', delimiter=',')

x_data = loaded_data[ :, 0:-1]
t_data = loaded_data[ :, [-1]]

# 데이터 차원 및 shape 확인
print("x_data.ndim = ", x_data.ndim, ", x_data.shape = ", x_data.shape)
print("t_data.ndim = ", t_data.ndim, ", t_data.shape = ", t_data.shape)
#print(x_data)
#print(t_data)

x_data.ndim =  2 , x_data.shape =  (25, 3)
t_data.ndim =  2 , t_data.shape =  (25, 1)


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [9]:
W = np.random.rand(3,1)  # 3X1 행렬
b = np.random.rand(1)  
print("W = \n", W, ", W.shape = ", W.shape, "\n b = ", b, ", b.shape = ", b.shape)

W = 
 [[0.68030557]
 [0.20900126]
 [0.17265499]] , W.shape =  (3, 1) 
 b =  [0.12349951] , b.shape =  (1,)


In [5]:
def errFunc(x, t):     # E(W, b)
    y = np.dot(x,W) + b
    return np.sum((t - y)**2) / len(x)
    
def errValue(x, t):      # 정답과 계산값과의 차이 --> 손실값(error value)
    return errFunc(x, t)

def numerical_derivative(e, x):     # 함수 e의 x에 대한 수치미분 --> E(W,b)를 W=[ ... ] 또는 b로 미분함.
    delta_x = 1e-4  # 0.0001        # 실제 미분함수를 구하지 않고 특정 값의 +- 0.0001 범위에서 기울기 구함
    grad = np.zeros_like(x)         # 주어진 각 값들에 대한 기울기 값 저장

    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])  # 다차원 배열 원소들의 순서참조 지원 함수
    while not it.finished:
        idx = it.multi_index        
        temp = x[idx]            # 주어진값(기울기 대상지점값)을 저장해두고 기울기 계산 후 다시 원상태로 되돌림
        x[idx] = temp + delta_x
        fx1 = e(x)                  # e(x+delta_x)   # 주어진 값의 약간의 증가분(+0.0001)에 대한 손실함수 값
        
        x[idx] = temp - delta_x 
        fx2 = e(x)                   # e(x-delta_x)   # 주어진 값의 약간의 감소분(-0.0001)에 대한 손실함수 값
        grad[idx] = (fx1 - fx2) / (2*delta_x)    # 주어진 값은 미세한 구간에서의 손실함수값의 변화량 --> 기울기
        
        x[idx] = temp            # 기울기값 구하기에 사용된 주어진 값의 사용이 끝난뒤 원래 값으로 되돌린다.
        it.iternext() 
    return grad

def grad_descent(x_data, t_data, W, b, learning_rate, repeat, outStep):
    f = lambda x : errFunc(x_data,t_data)   # errFunc()함수를 수치미분 함수의 인자로 넘기기 위해 

    print("Initial error value = {:.3f}".format(errValue(x_data, t_data)))
    print("Initial W = ", W.reshape(1,-1).round(3))
    print("Initial b = ", b.round(3))
    for step in range(repeat+1):        # 적당한 횟수만큼 경사하강 반복
        W -= learning_rate * numerical_derivative(f, W)
        b -= learning_rate * numerical_derivative(f, b)
        
        if (step % outStep == 0):       # 경사하강 반복 중간마다 손실값 출력
            print("Step = {:<5d}".format(step), "Error Value = {:.4f}".format(errValue(x_data, t_data)), 
                  "W =", W.reshape(1,-1).round(3), " b = ", b.round(3))

# 학습을 마친 후, 임의의 데이터에 대해 미래 값 예측 함수
def predict(x):         # 입력변수 x : numpy type
    y = np.dot(x,W) + b
    return y

In [31]:
W = np.random.rand(3,1)  # 3X1 행렬
b = np.random.rand(1)

learning_rate = .5e-4  # 1e-2, 1e-3 은 손실함수 값이 발산함
repeat = 10000
outStep = 1000
grad_descent(x_data, t_data, W, b, learning_rate, repeat, outStep)

print("="*50)
test_data = np.array([[90, 98, 81],[77,88,66]]            )
print("Prediction of data: {} is {}".format(test_data, predict(test_data)))

Initial error value = 3356.106
Initial W =  [[0.816 0.979 0.933]]
Initial b =  [0.977]
Step = 0     Error Value = 3090.9826 W = [[0.354 0.514 0.459]]  b =  [0.983]
Step = 1000  Error Value = 6.4010 W = [[0.417 0.531 1.055]]  b =  [0.973]
Step = 2000  Error Value = 6.2852 W = [[0.373 0.523 1.107]]  b =  [0.963]
Step = 3000  Error Value = 6.2776 W = [[0.361 0.526 1.116]]  b =  [0.953]
Step = 4000  Error Value = 6.2752 W = [[0.357 0.527 1.118]]  b =  [0.943]
Step = 5000  Error Value = 6.2731 W = [[0.356 0.528 1.118]]  b =  [0.932]
Step = 6000  Error Value = 6.2710 W = [[0.356 0.528 1.118]]  b =  [0.922]
Step = 7000  Error Value = 6.2689 W = [[0.356 0.528 1.119]]  b =  [0.912]
Step = 8000  Error Value = 6.2669 W = [[0.356 0.528 1.119]]  b =  [0.902]
Step = 9000  Error Value = 6.2649 W = [[0.356 0.528 1.119]]  b =  [0.892]
Step = 10000 Error Value = 6.2628 W = [[0.356 0.528 1.119]]  b =  [0.882]
Prediction of data: [[90 98 81]
 [77 88 66]] is [[175.28145651]
 [148.59173675]]


In [8]:
predict([98, 100, 94])

array([193.85413127])