In [1]:
import numpy as np

def sigmoid(x):
    return 1 / (1+np.exp(-x))

def cross_entropy(t, y):    # 크로스 엔트로피 함수
    delta = 1e-7        # log함수의 -무한대 발산 방지
    return -np.sum(t*np.log(y + delta) + (1-t)*np.log((1 - y)+delta))

def errFunc(x, t):
    z = np.dot(x,W) + b     # 선형회귀
    y = sigmoid(z)
    return cross_entropy(t, y)

def errValue(x, t):
    return  errFunc(x, t)  

def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
            
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index        
        temp = x[idx]
        x[idx] = temp + delta_x
        fx1 = f(x)  # f(x+delta_x)
        
        x[idx] = temp - delta_x 
        fx2 = f(x)  # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = temp 
        it.iternext()   
    return grad

def predict(x):
    z = np.dot(x,W) + b
    y = sigmoid(z)
    if y > 0.5:
        result = 1  # True
    else:
        result = 0  # False
    return y, result

def grad_descent(x_data, t_data, W, b, learning_rate, repeat, outStep):
    f = lambda x : errFunc(x_data,t_data)   # errFunc()함수를 다른 함수의 인자로 넘기기 위해 

    print("Initial error value = {:.3f}".format(errValue(x_data, t_data)))
    print("Initial W = ", W.reshape(1,-1).round(3))
    print("Initial b = ", b.round(3))
    for step in range(repeat+1):        # 적당한 횟수만큼 경사하강 반복
        W -= learning_rate * numerical_derivative(f, W)
        b -= learning_rate * numerical_derivative(f, b)
        
        if (step % outStep == 0):       # 경사하강 반복 중간마다 손실값 출력
            print("Step = {:<5d}".format(step), "Error Value = {:.4f}".format(errValue(x_data, t_data)),
                  "W =", W.reshape(1,-1).round(3), " b = ", b.round(3))

In [2]:
x_data = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20]).reshape(10, 1)
t_data = np.array([0, 0, 0, 0,  0,  0,  1,  1,  1,  1]).reshape(10, 1)
W = np.random.rand(1, 1)  # 1X1 행렬
b = np.random.rand(1)  
learning_rate = 1e-2  # 0.1, 0.01, 0.05, 0.001 일 때의 손실함수 값 비교
repeat = 10000
outStep = 1000

grad_descent(x_data, t_data, W, b, learning_rate, repeat, outStep)
predict(13)

Initial error value = 43.382
Initial W =  [[0.962]]
Initial b =  [0.479]
Step = 0     Error Value = 25.8140 W = [[0.547]]  b =  [0.422]
Step = 1000  Error Value = 1.6236 W = [[0.497]]  b =  [-6.227]
Step = 2000  Error Value = 1.2325 W = [[0.645]]  b =  [-8.189]
Step = 3000  Error Value = 1.0457 W = [[0.748]]  b =  [-9.552]
Step = 4000  Error Value = 0.9285 W = [[0.83]]  b =  [-10.633]
Step = 5000  Error Value = 0.8452 W = [[0.9]]  b =  [-11.545]
Step = 6000  Error Value = 0.7815 W = [[0.96]]  b =  [-12.343]
Step = 7000  Error Value = 0.7304 W = [[1.015]]  b =  [-13.057]
Step = 8000  Error Value = 0.6881 W = [[1.065]]  b =  [-13.707]
Step = 9000  Error Value = 0.6521 W = [[1.11]]  b =  [-14.306]
Step = 10000 Error Value = 0.6210 W = [[1.153]]  b =  [-14.864]


(array([[0.5310886]]), 1)

In [3]:
predict(33)

(array([[1.]]), 1)

In [ ]:
x_data = np.array([ [2, 4], [4, 11], [6, 6], [8, 5], [10, 7], [12, 16], [14, 8], [16, 3], [18, 7] ])
t_data = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1]).reshape(9, 1)
W = np.random.rand(2, 1)  # 2X1 행렬
b = np.random.rand(1)  

learning_rate = 1e-2  # 0.1, 0.01, 0.05, 0.001 일 때의 손실함수 값 비교
repeat = 80000
outStep = 2000

grad_descent(x_data, t_data, W, b, learning_rate, repeat, outStep)

Initial error value = 36.241
Initial W =  [[0.755 0.673]]
Initial b =  [0.917]
Step = 0     Error Value = 25.4084 W = [[0.555 0.414]]  b =  [0.877]
Step = 2000  Error Value = 0.9837 W = [[0.749 0.053]]  b =  [-6.877]
Step = 4000  Error Value = 0.6838 W = [[0.959 0.127]]  b =  [-9.293]
Step = 6000  Error Value = 0.5492 W = [[1.096 0.191]]  b =  [-10.925]
Step = 8000  Error Value = 0.4652 W = [[1.197 0.253]]  b =  [-12.216]
Step = 10000 Error Value = 0.4053 W = [[1.279 0.312]]  b =  [-13.307]
Step = 12000 Error Value = 0.3595 W = [[1.349 0.366]]  b =  [-14.261]
Step = 14000 Error Value = 0.3231 W = [[1.411 0.415]]  b =  [-15.111]
Step = 16000 Error Value = 0.2934 W = [[1.467 0.459]]  b =  [-15.879]
Step = 18000 Error Value = 0.2687 W = [[1.518 0.5  ]]  b =  [-16.58]
Step = 20000 Error Value = 0.2477 W = [[1.565 0.537]]  b =  [-17.225]
Step = 22000 Error Value = 0.2298 W = [[1.608 0.571]]  b =  [-17.822]
Step = 24000 Error Value = 0.2142 W = [[1.649 0.602]]  b =  [-18.378]
Step = 26000 Er

In [ ]:
test_data = np.array([3, 17]) # (예습, 복습) = (3, 17) => Fail (0)
predict(test_data)

(array([0.12862519]), 0)

In [ ]:
test_data = np.array([5, 8]) # (예습, 복습) = (5, 8) => Fail (0)
predict(test_data)

(array([0.00099104]), 0)

In [ ]:
test_data = np.array([7, 21]) # (예습, 복습) = (7, 21) => Pass (1)
predict(test_data)

(array([0.99998952]), 1)

In [ ]:
test_data = np.array([12, 0])  # (예습, 복습) = (12, 0) => Pass (1)
predict(test_data)

(array([0.63507501]), 1)